    #############################################################################
    #############################################################################
    ######### Managed by Terraform, not safe to change ##########################
    #############################################################################
    #############################################################################
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    server:
      extraEnvironmentVars:
        VAULT_SEAL_TYPE: awskms
        VAULT_AWSKMS_SEAL_KEY_ID: 8da29339-925e-4db3-95ef-7ff58ce301b4
        AWS_REGION: ap-south-1

      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::492737776546:role/sven-mumbai-vault
    ui:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: vault.sven-mumbai.local
